// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuv0NL7roQMtxPg4aiwo7p7j8Y2UshFeY',
    appId: '1:240540781672:web:6e2d36a09cdcabab7f7fdd',
    messagingSenderId: '240540781672',
    projectId: 'bloc-login-regis',
    authDomain: 'bloc-login-regis.firebaseapp.com',
    storageBucket: 'bloc-login-regis.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd3jwC6oDwqrbX7drIQvkUHiEA1ZKX9V8',
    appId: '1:240540781672:android:926c3017747ef72a7f7fdd',
    messagingSenderId: '240540781672',
    projectId: 'bloc-login-regis',
    storageBucket: 'bloc-login-regis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOyEBQsRLD8jLP6aFG-2kuFK_iE31vzQw',
    appId: '1:240540781672:ios:aed75c6243f179b17f7fdd',
    messagingSenderId: '240540781672',
    projectId: 'bloc-login-regis',
    storageBucket: 'bloc-login-regis.firebasestorage.app',
    iosBundleId: 'com.example.blocLoginRegisterFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOyEBQsRLD8jLP6aFG-2kuFK_iE31vzQw',
    appId: '1:240540781672:ios:aed75c6243f179b17f7fdd',
    messagingSenderId: '240540781672',
    projectId: 'bloc-login-regis',
    storageBucket: 'bloc-login-regis.firebasestorage.app',
    iosBundleId: 'com.example.blocLoginRegisterFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuv0NL7roQMtxPg4aiwo7p7j8Y2UshFeY',
    appId: '1:240540781672:web:fc67a6caa9d2b9627f7fdd',
    messagingSenderId: '240540781672',
    projectId: 'bloc-login-regis',
    authDomain: 'bloc-login-regis.firebaseapp.com',
    storageBucket: 'bloc-login-regis.firebasestorage.app',
  );
}
